/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/cloudflare/wrangler.jsonc --include-runtime=false apps/cloudflare/worker-configuration.d.ts` (hash: 763af93de9f7e02a8c8358261e4cfdec)
interface __BaseEnv_Env {
	CONTACT_EMAIL: "research-api@ogleits.com";
	MCP_BEARER_TOKEN: string;
	NCBI_API_KEY: string;
	ALLOWED_HOSTNAMES: string;
	ALLOWED_ORIGIN_HOSTNAMES: string;
}
declare namespace Cloudflare {
	interface StagingEnv {
		CONTACT_EMAIL: "research-api@ogleits.com";
		MCP_BEARER_TOKEN: string;
		NCBI_API_KEY: string;
		ALLOWED_HOSTNAMES: string;
		ALLOWED_ORIGIN_HOSTNAMES: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTACT_EMAIL" | "MCP_BEARER_TOKEN" | "NCBI_API_KEY" | "ALLOWED_HOSTNAMES" | "ALLOWED_ORIGIN_HOSTNAMES">> {}
}
