/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/cloudflare/wrangler.jsonc --include-runtime=false apps/cloudflare/worker-configuration.d.ts` (hash: 46494a2a92d5add995692e403e89b491)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	CONTACT_EMAIL: "research-api@ogleits.com";
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	COOKIE_ENCRYPTION_KEY: string;
	NCBI_API_KEY: string;
	ALLOWED_HOSTNAMES: string;
	ALLOWED_ORIGIN_HOSTNAMES: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		OAUTH_KV: KVNamespace;
		CONTACT_EMAIL: "research-api@ogleits.com";
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		COOKIE_ENCRYPTION_KEY: string;
		NCBI_API_KEY: string;
		ALLOWED_HOSTNAMES: string;
		ALLOWED_ORIGIN_HOSTNAMES: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTACT_EMAIL" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "COOKIE_ENCRYPTION_KEY" | "NCBI_API_KEY" | "ALLOWED_HOSTNAMES" | "ALLOWED_ORIGIN_HOSTNAMES">> {}
}
