/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false apps/cloudflare/worker-configuration.d.ts` (hash: 94610639bddb056d9c24c9d0a937a701)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	USER_DATA_KV: KVNamespace;
	USAGE_ANALYTICS: AnalyticsEngineDataset;
	MCP_ACCOUNT_RATE_LIMITER: RateLimit;
	CONTACT_EMAIL: "research-api@ogleits.com";
	COOKIE_ENCRYPTION_KEY: string;
	USER_DATA_ENCRYPTION_KEY: string;
	NCBI_API_KEY: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	ALLOWED_HOSTNAMES: string;
	ALLOWED_ORIGIN_HOSTNAMES: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTACT_EMAIL" | "COOKIE_ENCRYPTION_KEY" | "USER_DATA_ENCRYPTION_KEY" | "NCBI_API_KEY" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "ALLOWED_HOSTNAMES" | "ALLOWED_ORIGIN_HOSTNAMES">> {}
}
